package terminals;

import javax.smartcardio.*;
import java.security.*;
import java.security.interfaces.RSAPrivateKey;
import java.security.interfaces.RSAPublicKey;
import java.nio.ByteBuffer;
import java.time.LocalDate;
import org.bouncycastle.jce.provider.BouncyCastleProvider;

/**
 * Controlled Access Terminal (CAT) - Updated for 203-byte payload.
 * Matches the applet offset: Sigma2(64) + Cert_T(71) + Sigma1(64) + Date(4) = 203 bytes.
 */
public class ControlledAccessTerminal extends BaseTerminal {

    static {
        Security.addProvider(new BouncyCastleProvider());
    }

    private static final byte CLA_PROPRIETARY = (byte) 0xB0;
    private static final byte INS_CHECKIN_T2 = (byte) 0x21; 
    private static final byte INS_GET_NONCE = (byte) 0x21; 

    private RSAPrivateKey terminalPrivateKey;
    private byte[] terminalCertificate; // Cert_T (71 bytes)
    private byte[] masterSignature;      // Sigma1 (64 bytes)

    public ControlledAccessTerminal() {
        try {
            // initialize terminal-specific RSA keys 
            KeyPairGenerator keyGen = KeyPairGenerator.getInstance("RSA", "BC");
            keyGen.initialize(512);
            KeyPair kp = keyGen.generateKeyPair();
            this.terminalPrivateKey = (RSAPrivateKey) kp.getPrivate();
            RSAPublicKey terminalPublicKey = (RSAPublicKey) kp.getPublic();

            // simulate Cert_T (ID_T + Modulus + Exponent) for mutual authentication
            this.terminalCertificate = new byte[71];
            byte[] terminalId = {0x0A, 0x0B, 0x0C, 0x0D};
            byte[] modulus = terminalPublicKey.getModulus().toByteArray();
            byte[] exponent = terminalPublicKey.getPublicExponent().toByteArray();

            System.arraycopy(terminalId, 0, terminalCertificate, 0, 4);
            // modulus might be longer than 64 bytes due to leading zero, adjust accordingly
            int modOffset = (modulus.length > 64) ? 1 : 0;
            System.arraycopy(modulus, modOffset, terminalCertificate, 4, 64);
            System.arraycopy(exponent, 0, terminalCertificate, 68, Math.min(exponent.length, 3));

            // placeholder for Sigma1 (Master Signature) 
            // In a real system, this would be generated by the MasterTerminal
            this.masterSignature = new byte[64]; 
            
            System.out.println("[CAT] Terminal credentials initialized.");
        } catch (Exception e) {
            System.err.println("[CAT] Initialization error: " + e.getMessage());
        }
    }

    private void processCheckinTier2() throws Exception {
        System.out.println("\n[CAT] Starting Tier 2 Check-in...");

        // verify card and extract member ID from certificate
        byte[] memberId = verifyAndGetIdFromCert();
        System.out.println("[CAT] Card Verified: " + bytesToHex(memberId));

        // retrieve 16-byte Nonce from card for freshness
        ResponseAPDU nonceRes = send(new CommandAPDU(CLA_PROPRIETARY, INS_GET_NONCE, 0x00, 0x00));
        byte[] nonce = nonceRes.getData();

        // prepare data for Sigma2: Nonce + Current Date
        byte[] currentDate = getFormattedDate();
        
        //sign [Nonce + CurrentDate] with Terminal's Private Key to create Sigma2
        ByteBuffer signBuffer = ByteBuffer.allocate(nonce.length + currentDate.length);
        signBuffer.put(nonce);
        signBuffer.put(currentDate);

        Signature sig = Signature.getInstance("SHA1withRSA", "BC");
        sig.initSign(terminalPrivateKey);
        sig.update(signBuffer.array());
        byte[] sigma2 = sig.sign(); // 64 bytes

        //construct 203-byte payload: Sigma2(64) + Cert_T(71) + Sigma1(64) + Date(4)
        ByteBuffer payload = ByteBuffer.allocate(203);
        payload.put(sigma2);              // 0..63
        payload.put(terminalCertificate); // 64..134
        payload.put(masterSignature);     // 135..198
        payload.put(currentDate);         // 199..202 (Corrisponde a OFFSET_CDATA + 199 nell'applet)

        System.out.println("[CAT] Sending 203-byte mutual auth payload...");
        ResponseAPDU res = send(new CommandAPDU(CLA_PROPRIETARY, INS_CHECKIN_T2, 0x00, 0x00, payload.array()));

        if (res.getSW() == 0x9000) {
            System.out.println("[CAT] ACCESS GRANTED. Daily Counter: " + res.getData()[0]);
        } else {
            System.err.println("[CAT] ACCESS DENIED. SW: " + Integer.toHexString(res.getSW()));
        }
    }

    private byte[] getFormattedDate() {
        LocalDate now = LocalDate.now();
        return new byte[] {
            (byte) (now.getYear() / 100),
            (byte) (now.getYear() % 100),
            (byte) now.getMonthValue(),
            (byte) now.getDayOfMonth()
        };
    }

    public void startProcess() {
        if (!connect()) return;
        try {
            processCheckinTier2();
        } catch (Exception e) {
            System.err.println("[CAT] Error: " + e.getMessage());
        } finally {
            disconnect(false);
        }
    }

    public static void main(String[] args) throws Exception {
        ControlledAccessTerminal cat = new ControlledAccessTerminal();
        cat.loadMasterPublicKey("master_public.key");
        cat.startProcess();
    }
}